### ISSUE TITLE
spaces in extended search fields

### ISSUE THREAD

**Issue by fbanados** [UAlbertaALTLab/korp-config#3]
Since CWB annoyingly cannot deal with spaces and slashes, search for complex glosses can become cumbersome.

The extended search fields should automatically deal with this case and escape the characters so that search works.

For documentation (and consistency in future corpora), we will use the `&#x20;` HTML entity to represent a whitespace, and the `&sol;` entity for a forward slash.

**Comment by fbanados** [comment]
Currently deployed fix works in `korp.altlab.dev`

![Screenshot 2024-09-20 at 3 24 32 PM](https://github.com/user-attachments/assets/6bfc64dc-1644-4b03-aa60-135b7086273a)

**Comment by fbanados** [comment]
@aarppe

**Comment by aarppe** [comment]
Very useful improvement. It is worthwhile that the special characters end up in the Advanced Search window, since those are current needed - though the ideal solution would be able to deal with spaces (and slashes) as is.
